### ISSUE TITLE
(BUG) COMOPANY REPS /  translations problem 'profile.'

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/exhibitors#78] opened 2023-01-16 11:48 UTC
Hello, @az 

I have some problems with these translations: 

profile.cname2
profile.fname
profile.lname
profile.position
profile.phone

The translations are added in localise, but they don't appear in the exhibitor's panel

**Comment by az** [comment] 2023-01-16 12:21
@klaudia2209 asked you 100000 times...... URL or screenshot ?  company reps?

why are you mentioning not related issues together? this isnt a chat ...its tool to make things done.

**Comment by az** [comment] 2023-01-16 12:22
(BUG) - something (seems or is) broken
(MAINTENANCE) - something is doable (no errors) and must be done

**Comment by klaudia2209** [comment] 2023-01-16 12:25
When I added screenshots, you said that you know it so well and you don't need so many screenshots... 
I added it as maintenance, because the page still works, even without it ;) 
It's a tool to communicate as well...

I found it in RVPs

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/118257251/212677578-380fad04-f9ec-42dd-ab8f-b770f0e38d9e.png">

and in Company representatives

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/118257251/212677770-e1e9ffdf-be63-423d-9992-35617087854e.png">

**Comment by az** [comment] 2023-01-16 12:47
@klaudia2209 jak na cos odpowiadasz to nie wybieraj 1 z 2... napisalem **URL** albo screenshot.......  moglo byc https://account.ecommerceberlin.com/#/representatives/create i bym nie musial sie domyslac

dzieki za potwierdzenie ze chodzi o /representatives/create

**Comment by az** [comment] 2023-01-16 12:49
duplicate of https://github.com/ecommerceberlin/exhibitors/issues/22

**Comment by az** [comment] 2023-01-16 12:56
@klaudia2209 

sprawdzilem w localise TEHowym - inne etykietki trzeba wprowadzic do localise - 

resources.representatives.fields.profile.fname
resources.representatives.fields.profile.lname
resources.representatives.fields.profile.position
resources.representatives.fields.profile.phone

**Closed by az** 2023-01-16 12:56 UTC

**Comment by az** [comment] 2023-01-16 13:28
@klaudia2209 to dodaj please przed jutrzejsza wysylka :)

**Comment by klaudia2209** [comment] 2023-01-16 14:16
Ok, dodane w 'COMPANY REPRESENTATIVES', ale jeszcze prośba o sprawdzenie RVPS: 

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/118257251/212698325-658fd12f-c898-45cc-9c64-a98e73af0abc.png">

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/118257251/212698755-ec89ada4-3cf9-46af-a792-79996b17bd4b.png">

**Comment by az** [comment] 2023-01-16 14:24
@klaudia2209 wrocimy do tematu jak bedziemy odpalace te ficzery, ok?

ja masz czas to ogarnij tlumaczenia masterclasses (pamietaj ze dalem Tobie 2 pliki CSV gdzie masz wszystko z TEHu... edytor, cmd+f i jechane

**Comment by klaudia2209** [comment] 2023-01-16 14:57
Dobra, będę działać! To otwórzmy to issue, żeby nie zapomnieć, jak możemy
